language: r

cache: packages

sudo: required

script:
  - Rscript "R/render_site.R"

warnings_are_errors: false

notifications:
  email:
    recipients:
      - nicolas.casajus@gmail.com

r_packages:
  - devtools
  - yaml
