---
title: |
    | Formation Pandoc's Markdown -- Exercice n°3
    | Créer un document dynamique (suite)
lang: french
fontsize: 11pt
output:
    pdf_document:
        toc: false
---

\vspace{2.5cm}

# Contexte

Votre article a été refusé par l'éditeur en chef de _Proceedings of the National Academy of Sciences_. Une critique majeure est le faible nombre d'observations. Entre temps, votre campagne de terrain s'est enrichie d'un nouvel été de terrain et votre assistant a recolté de nouvelles mesures de longueur et largeur de pétales chez l'iris versicolore.

D'autres critiques majeures ont été soulevés, et vous décidez de soumettre une nouvelle version de votre manuscrit au journal _Global Ecology and Biogeography_ en refaisant les mêmes analyses sur le jeux de données augmenté. Et vous croisez les doigts...

# Instructions

1. Copier le fichier `exercice2.rmd` et renommez-le `exercice3.rmd`

1. Modifier le YAML de manière à générer une bibliographie dans le style de la revue _Global Ecology and Biogeography_

1. Refaites les mêmes analyses sur le nouveau jeu de données `data_v2.txt`

1. Convertissez-le en PDF à l'aide de la fonction R `render()`

# Notes

Cela devrait vous prendre moins d'une minute !
