---
title: |
    | Formation Pandoc's Markdown -- Exercice n°2
    | Créer un document dynamique
lang: french
fontsize: 11pt
output:
    pdf_document:
        toc: false
---

\vspace{2.5cm}

# Objectifs

Au cours de cet exercice, vous allez apprendre à créer un document scientifique dynamique. Plus précisément, vous allez intégrer dans le coeur du document des références bibliographiques (et générer la bibliographie dans un style prédéfini) ainsi que des fragments de code R embarqués pour réaliser les analyses et figures.



# Instructions

1. Téléchargez les fichiers à cette adresse : [http://ahasverus.github.io/md-lecture/exercice2.zip](http://ahasverus.github.io/md-lecture/exercice2.zip)

1. Cette archive ZIP contient différents fichiers/répertoires :

    - `csl/`, répertoire contenant les styles bibliographiques,
    - `data/`, répertoire contenant les données à analyser,
    - `img/`, répertoire contenant les images à intégrer dans le document,
    - `exercice2.rmd`, le fichier dans lequel vous devrez insérer les balises Markdown,
    - `exercice2_final.pdf`, le PDF final auquel votre document devra ressembler.

1. Insérer les références tel qu'indiqué dans le document `exercice2.rmd`. Les références sont présentes dans le fichier `includes/references.bib`.

1. Modifier le YAML de manière à générer une bibliographie dans le style de la revue _Proceedings of the National Academy of Sciences (PNAS)_

1. Compléter les blocs de code R. Dans le dernier bloc de code R, vous n'aurez rien à changer ; c'est cadeau !

1. Compléter les _inline_ code R. Voici un exemple pour le nombre de lignes dans la table (mettre le tout entre un seul accent grave) : **r nrow(tab)**

1. N'oubliez pas les autres balises Markdown (titres, italique, etc.)

1. Convertissez-le en PDF à l'aide de la fonction R `render()`

# Notes

La formation est disponible à cette adresse :  [http://ahasverus.github.io/md-lecture/](http://ahasverus.github.io/md-lecture/). N'hésitez pas à la consulter pour trouver les balises Markdown nécessaires.
