---

---

```{r echo = FALSE, eval = TRUE}
# Importation des donnees
tab <- read.delim("./data/data_v1.txt")
```

```{r echo = FALSE, eval = TRUE}
# Ajustement d'un modele lineaire
mod <- lm(Petal.Length ~ Petal.Width, data = tab)

# Stockage des resultats
coefs <- round(mod$coefficients, 2)
rsq   <- round(summary(mod)$r.squared, 2)

# Predictions pour droite de regression
dat <- data.frame(Petal.Width = seq(min(tab$Petal.Width),
                                    max(tab$Petal.Width),
                                    length.out = 100))
ypred <- predict(mod, dat, se = T)
```

```{r fig.width = , fig.}
# Scatterplot des points
plot(tab$Petal.Width, tab$Petal.Length,
     pch = 19, las = 1, ylim = c(3, 5.5),
     xlab = 'Largeur de pétale',
     ylab = 'Longueur de pétale')

# Ajout de l'enveloppe d'incertitude
polygon(c(dat[ , 'Petal.Width'], dat[nrow(dat):1, 'Petal.Width']),
        c(ypred$fit + ypred$se.fit, (ypred$fit - ypred$se.fit)[nrow(dat):1]),
        col = '#aaaaaa88', border = NA)

# Ajout de la droite de regression
lines(dat[ , 'Petal.Width'], ypred$fit, lwd = 2)

# Ajout d'un titre
title('Iris versicolor', font.main = 4)
```
