---
title: |
    | Formation Pandoc's Markdown -- Exercice n°1
    | Maîtriser les bases du langage
lang: french
fontsize: 11pt
output:
    pdf_document:
        toc: false
---

\vspace{2.5cm}

# Objectifs

Cet exercice a pour but de vous familiariser avec les bases du langage Pandoc's Markdown. Plus précisément, vous allez mettre en application les notions de la formation suivantes : division du document, mise en évidence du texte, listes numérotées, listes à puces, lien hypertexte, note de bas de page, insertion d'image et création de tableaux.

À partir d'un fichier `texte` brut, vous allez devoir ajouter les balises Markdown adéquates afin que le document final produit (au format PDF) ressemble le plus possible au document `exercice1_final.pdf` (voir Instructions ci-dessous).

# Instructions

1. Téléchargez les fichiers à cette adresse : [http://ahasverus.github.io/md-lecture/exercice1.zip](http://ahasverus.github.io/md-lecture/exercice1.zip)

1. Cette archive ZIP contient trois fichiers :

    - `exercice1.rmd`, le fichier dans lequel vous devrez insérer les balises Markdown,
    - `exercice1_final.pdf`, le PDF final auquel votre document devra ressembler,
    - `solar.jpg`, une image à insérer dans le document (placée dans le répertoire `img/`).

1. Ajoutez les balises Markdown dans le fichier `exercice1.rmd`

1. Convertissez-le en PDF à l'aide de la fonction R `render()`

# Notes

La formation est disponible à cette adresse :  [http://ahasverus.github.io/md-lecture/](http://ahasverus.github.io/md-lecture/). N'hésitez pas à la consulter pour trouver les balises Markdown nécessaires. Consultez en particulier la dernière diapositive (La fonction `render()` -- Erreurs possibles)
